# Exported from Render on 2026-05-16T14:51:39Z
version: "1"
projects:
- name: iredev-agile
  environments:
  - name: Production
    services:
    - type: web
      name: iredev-agile
      runtime: python
      repo: https://github.com/Trungpham2k4/iredev-agile
      plan: free
      envVars:
      - key: CORS_ORIGIN
        sync: false
      - key: IREDEV_PG_CONNECTION
        sync: false
      - key: PORT
        sync: false
      - key: COOKIE_SAMESITE
        sync: false
      - key: COOKIE_SECURE
        sync: false
      - key: BLACKLIST_SWEEP_INTERVAL_SECONDS
        sync: false
      - key: REFRESH_TOKEN_TTL_SECONDS
        sync: false
      - key: ACCESS_TOKEN_TTL_SECONDS
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        sync: false
      region: singapore
      buildCommand: pip install -r requirements.txt
      startCommand: python -m src.server.app
      autoDeployTrigger: commit
      rootDir: backend
      previews:
        generation: automatic
    - type: web
      name: iredev-agile-fe
      runtime: static
      repo: https://github.com/Trungpham2k4/iredev-agile
      envVars:
      - key: VITE_WS_BASE_URL
        sync: false
      - key: VITE_WS_RECONNECT_DELAY_MS
        sync: false
      - key: VITE_REQUEST_TIMEOUT_MS
        sync: false
      - key: VITE_API_BASE_URL
        sync: false
      buildCommand: npm install;npm run build
      staticPublishPath: dist
      autoDeployTrigger: commit
      rootDir: frontend
    databases:
    - name: postgres-agile
      databaseName: iredev
      user: iredev_user
      plan: free
      region: singapore
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "16"
